<?php
namespace Teach\Domain\Lesplan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 13:44:20.
 */
class BeginsituatieTest extends \Teach\DomainTest
{
    public function testDocument()
    {
        $object = new Beginsituatie("De les!", [
            'doelgroep' => [
                'beschrijving' => "De doelgroep",
                'ervaring' => "geen",
                'grootte' => '16 personen'
            ],
            'starttijd' => "08:45",
            'eindtijd' => "10:20",
            'duur' => "90 minuten",
            'ruimte' => "werkplaats met computers",
            'overige' => "nvt"
        ], ["post-its"], ["nog ademen"]);
        $html = $object->document(\Test\Helper::implementDocumenter());
        $this->assertEquals('section2:De les!...3:Beginsituatie...: a:5:{i:0;a:2:{s:9:"doelgroep";s:12:"De doelgroep";s:8:"ervaring";s:4:"geen";}i:1;a:1:{s:13:"groepsgrootte";s:11:"16 personen";}i:2;a:1:{s:4:"tijd";s:40:"van 08:45 tot 10:20 (90 minuten minuten)";}i:3;a:1:{s:6:"ruimte";s:24:"werkplaats met computers";}i:4;a:1:{s:7:"overige";s:3:"nvt";}}...3:Media...ul: a:1:{i:0;s:8:"post-its";}...3:Leerdoelen...<p>Na afloop van de les kan de student:</p>...ul: a:1:{i:0;s:10:"nog ademen";}', $html);
    }
}
