services:
  - mysql
language: php
before_install:
  - mysql -e 'CREATE DATABASE teach;'
  - phpenv config-add travis.php.ini
  - printf "\n" | pecl install imagick
install:
  - echo '|1|+2lC+ZMLuAow30SKKRkXW8+SIJg=|0063B3li+aMWB5BQrcGR16of2X0= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvOs1rTXd6KsK7bmo/2dQiKtbeekF4/fXAMUM91y4chbPkLSd9zCqDaxhY1mwU0h5stWBRSm3K0WyrEHaUO8/BIknYnDyRUgcMf4WtichX7YD776HeSZZNOixh4iQLc/JxNxy5DXILytuTFl4/fTlhlXrGnxrleljUtzid3y/ultqAsVYcMt5lybYdO/g8thi+FqtnX27z4qh2y8qQgZ5AJ+e/ic8TQAxW/FI4+bC6ZNC7JEQCzkl48qbrcmXfilPzoPOP9EV3WlwPuftir9pSpizEK4SkPNYABOauzT5ystgiEaThqD0aww4vIAP0dJNJwxHCrvByqWKfD3CGcE4kQ==' >> $HOME/.ssh/known_hosts
  - composer install
  - "./migrate-database"
  - php ./cli/teach.php regenerateTDBM
php:
  - '7.3'

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f753f987fe65_key -iv $encrypted_f753f987fe65_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -p 7685 u28492p22384@web0115.zxcs.nl "cd domains/teach.pulledbits.org; ./deploy.sh"
  on:
    branch: master