services:
  - mysql
language: php
addons:
  ssh_known_hosts: web0115.zxcs.nl:7685
before_install:
  - mysql -e 'CREATE DATABASE teach;'
  - phpenv config-add travis.php.ini
  - printf "\n" | pecl install imagick
install:
  - composer install
  - "./migrate-database"
  - php regenerateTDBM.php
php:
  - '7.3'

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f753f987fe65_key -iv $encrypted_f753f987fe65_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --rsh='ssh -p7685' --quiet $TRAVIS_BUILD_DIR u28492p22384@web0115.zxcs.nl:domains/teach.pulledbits.org/
  on:
    branch: master