services:
- mysql
language: php
before_install:
- openssl aes-256-cbc -K $encrypted_f753f987fe65_key -iv $encrypted_f753f987fe65_iv
  -in teach-242612-3107c084626f.json.enc -out teach-242612-3107c084626f.json
  -d
- mysql -e 'CREATE DATABASE teach;'
- phpenv config-add travis.php.ini
- printf "\n" | pecl install imagick
install:
- echo '|1|+2lC+ZMLuAow30SKKRkXW8+SIJg=|0063B3li+aMWB5BQrcGR16of2X0= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvOs1rTXd6KsK7bmo/2dQiKtbeekF4/fXAMUM91y4chbPkLSd9zCqDaxhY1mwU0h5stWBRSm3K0WyrEHaUO8/BIknYnDyRUgcMf4WtichX7YD776HeSZZNOixh4iQLc/JxNxy5DXILytuTFl4/fTlhlXrGnxrleljUtzid3y/ultqAsVYcMt5lybYdO/g8thi+FqtnX27z4qh2y8qQgZ5AJ+e/ic8TQAxW/FI4+bC6ZNC7JEQCzkl48qbrcmXfilPzoPOP9EV3WlwPuftir9pSpizEK4SkPNYABOauzT5ystgiEaThqD0aww4vIAP0dJNJwxHCrvByqWKfD3CGcE4kQ=='
  >> $HOME/.ssh/known_hosts
- composer install
- "./migrate-database"
- php ./cli/teach.php regenerateTDBM
php:
- '7.2'
deploy:
  provider: gae
  keyfile: teach-242612-3107c084626f.json
  project: teach-242612
