services:
  - mysql
language: php
before_install:
  - mysql -e 'CREATE DATABASE teach;'
  - phpenv config-add travis.php.ini
  - printf "\n" | pecl install imagick
install:
  - ./install.sh
php:
  - '7.4'
deploy:
  provider: script
  script: curl -Ss https://teach.rikmeijer.nl/update.php
  on:
    branch: master
