runtime: php73
entrypoint: serve src/public/index.php
#api_version: 1

handlers:
  - url: /css
    static_dir: src/public/css

  - url: /img
    static_dir: src/public/img

  - url: /webboard
    static_dir: src/public/webboard