<?php return [
    'APP_ENV' => 'local',
    'APP_DEBUG' => 'true',
    'APP_LOG_LEVEL' => 'debug',
    'APP_KEY' => 'base64:AwzyvEP+atLtJPjnNhXGGCY7Lm0Iz4vdPeDsK4lUFfY=',
    'APP_URL' => 'http://teach.local.pulledbits.org',
    '#DB_CONNECTION' => 'sqlite',
    'DB_CONNECTION' => 'mysql',
    'DB_HOST' => '127.0.0.1',
    'DB_PORT' => '3306',
    'DB_DATABASE' => 'teach',
    'DB_USERNAME' => 'teach',
    'DB_PASSWORD' => 'teach',
    'DB_PREFIX' => '',
];