<?php
namespace Teach;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 13:44:20.
 */
abstract class DomainTest extends \PHPUnit_Extensions_Database_TestCase
{

    /**
     *
     * @var \PDO
     */
    static $pdo;

    private $connection;

    /**
     *
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
        if ($this->connection === null) {
            self::$pdo = new \PDO('mysql:host=localhost;dbname=teach_test', 'teach_test');
            // clear tables
            $truncates = self::$pdo->query("
                SELECT Concat('TRUNCATE TABLE ',table_schema,'.',TABLE_NAME, ';')
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE  table_schema in ('teach_test');
            ")->fetchAll(\PDO::FETCH_NUM);
            self::$pdo->exec('SET FOREIGN_KEY_CHECKS=0');
            foreach ($truncates as $truncate) {
                self::$pdo->exec($truncate[0]);
            }
            self::$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
            $this->connection = $this->createDefaultDBConnection(self::$pdo);
        }
        
        return $this->connection;
    }

    /**
     *
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
        return $this->createXMLDataSet(dirname(__DIR__) . DIRECTORY_SEPARATOR . 'teach.xml');
    }
}
