<?php
namespace Teach\Entities;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 13:44:20.
 */
class ContactmomentTest extends \Teach\EntitiesTest
{
    public function testCreateLesplan()
    {   
        $factory = new Factory(self::$pdo);
        $object = $factory->createContactmoment('1');
        $factory = new \Teach\Interactors\Web\Lesplan\Factory();
        $lesplanlayout = $object->createLesplan($factory);
        $this->assertInstanceOf('\Teach\Interactors\Web\Lesplan', $lesplanlayout);
    }
}
