<?php
namespace Teach\Entities;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 13:44:20.
 */
class FactoryTest extends \Teach\EntitiesTest
{
    public function testQuery()
    {   
        $object = new Factory(self::$pdo);
        $contactmomenten = $object->query("SELECT * FROM contactmoment WHERE id = 1");
        $this->assertEquals('1', $contactmomenten[0]['les_id']);
        
    }
    
    public function testCreateContactmoment()
    {
        $object = new Factory(self::$pdo);
        $this->assertInstanceOf('\Teach\Entities\Contactmoment', $object->createContactmoment('1'));
    }

    public function testGetBeginsituatie()
    {
        $object = new Factory(self::$pdo);
        $beginsituatie = $object->getBeginsituatie('1');
        $this->assertEquals('eerstejaars HBO-studenten', $beginsituatie['doelgroep']['beschrijving']);
        $this->assertEquals('geen', $beginsituatie['doelgroep']['ervaring']);
        $this->assertEquals('16 personen', $beginsituatie['doelgroep']['grootte']);
        $this->assertEquals('08:45', $beginsituatie['starttijd']);
        $this->assertEquals('10:20', $beginsituatie['eindtijd']);
        $this->assertEquals('95', $beginsituatie['duur']);
        $this->assertEquals('beschikking over vaste computers', $beginsituatie['ruimte']);
        $this->assertEquals('nvt', $beginsituatie['overige']);
    }
}
