<?php
namespace Teach\Entities;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 13:44:20.
 */
class FactoryTest extends \Teach\EntitiesTest
{
    public function testQuery()
    {   
        $object = new Factory(self::$pdo);
        $contactmomenten = $object->query("SELECT * FROM contactmoment WHERE id = 1");
        $this->assertEquals('1', $contactmomenten[0]['les_id']);
        
    }
    
    public function testCreateContactmoment()
    {
        $object = new Factory(self::$pdo);
        $this->assertInstanceOf('\Teach\Entities\Contactmoment', $object->createContactmoment('1'));
    }
}
