<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractContactmomentDao;

/**
 * The ContactmomentDao class will maintain the persistence of Contactmoment class into the contactmoment table.
 */
class ContactmomentDao extends AbstractContactmomentDao
{
}
