<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Beans\Module;
use rikmeijer\Teach\Daos\Generated\AbstractContactmomentDao;
use TheCodingMachine\TDBM\ResultIterator;

/**
 * The ContactmomentDao class will maintain the persistence of Contactmoment class into the contactmoment table.
 */
class ContactmomentDao extends AbstractContactmomentDao
{
    public function findContactmomentenForUserByModule(string $owner, Module $module) : ResultIterator {
        return $this->find('module.naam = :moduleName AND contactmoment.owner = :owner', ['moduleName' => $module->getNaam(), 'owner' => $owner]);
    }

    public function findContactmomentenTodayForUser(string $owner) : ResultIterator {
        return $this->find('DATE(contactmoment.starttijd) = curdate() AND contactmoment.owner = :owner', ['owner' => $owner]);
    }
}
