<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractDoctrineMigrationVersionDao;

/**
 * The DoctrineMigrationVersionDao class will maintain the persistence of DoctrineMigrationVersion class into the doctrine_migration_versions table.
 */
class DoctrineMigrationVersionDao extends AbstractDoctrineMigrationVersionDao
{
}
