<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractLesDao;

/**
 * The LesDao class will maintain the persistence of Les class into the les table.
 */
class LesDao extends AbstractLesDao
{
}
