<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractLesweekDao;

/**
 * The LesweekDao class will maintain the persistence of Lesweek class into the lesweek table.
 */
class LesweekDao extends AbstractLesweekDao
{
}
