<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractMigrationDao;

/**
 * The MigrationDao class will maintain the persistence of Migration class into the migrations table.
 */
class MigrationDao extends AbstractMigrationDao
{
}
