<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractModuleDao;

/**
 * The ModuleDao class will maintain the persistence of Module class into the module table.
 */
class ModuleDao extends AbstractModuleDao
{
}
