<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractPasswordResetDao;

/**
 * The PasswordResetDao class will maintain the persistence of PasswordReset class into the password_resets table.
 */
class PasswordResetDao extends AbstractPasswordResetDao
{
}
