<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractRatingDao;

/**
 * The RatingDao class will maintain the persistence of Rating class into the rating table.
 */
class RatingDao extends AbstractRatingDao
{
}
