<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractRatingwaardeDao;

/**
 * The RatingwaardeDao class will maintain the persistence of Ratingwaarde class into the ratingwaarde table.
 */
class RatingwaardeDao extends AbstractRatingwaardeDao
{
}
