<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractUseremailaddressDao;

/**
 * The UseremailaddressDao class will maintain the persistence of Useremailaddress class into the useremailaddresses table.
 */
class UseremailaddressDao extends AbstractUseremailaddressDao
{
}
