<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Daos;

use rikmeijer\Teach\Daos\Generated\AbstractUserDao;

/**
 * The UserDao class will maintain the persistence of User class into the users table.
 */
class UserDao extends AbstractUserDao
{
}
