<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractContactmoment;

/**
 * The Contactmoment class maps the 'contactmoment' table in database.
 */
class Contactmoment extends AbstractContactmoment
{
}
