<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractContactmoment;

/**
 * The Contactmoment class maps the 'contactmoment' table in database.
 */
class Contactmoment extends AbstractContactmoment
{
    public function getAverageRating() {
        $contactmomentratings = $this->getRating();
        if (count($contactmomentratings) === 0) {
            return 0;
        }
        $value = 0;
        foreach ($contactmomentratings as $contactmomentrating) {
            $value += $contactmomentrating->getWaarde()->getNaam();
        }
        return round($value / count($contactmomentratings), 1);
    }

    public function isActive() : bool {
        return $this->getStarttijd()->getTimestamp() <= time() && $this->getStarttijd()->getTimestamp() >= time();
    }
    public function hasPast() : bool {
        return $this->getEindtijd()->getTimestamp() <= time();
    }

    public function getKalenderweek() : string {
        return $this->getLes()->getLesweek()->getKalenderweek();
    }
    public function getBlokweek() : string {
        return $this->getLes()->getLesweek()->getBlokweek();
    }

}
