<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractDoctrineMigrationVersion;

/**
 * The DoctrineMigrationVersion class maps the 'doctrine_migration_versions' table in database.
 */
class DoctrineMigrationVersion extends AbstractDoctrineMigrationVersion
{
}
