<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractMigration;

/**
 * The Migration class maps the 'migrations' table in database.
 */
class Migration extends AbstractMigration
{
}
