<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractModule;

/**
 * The Module class maps the 'module' table in database.
 */
class Module extends AbstractModule
{
}
