<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractPasswordReset;

/**
 * The PasswordReset class maps the 'password_resets' table in database.
 */
class PasswordReset extends AbstractPasswordReset
{
}
