<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace rikmeijer\Teach\Beans;

use rikmeijer\Teach\Beans\Generated\AbstractRatingwaarde;

/**
 * The Ratingwaarde class maps the 'ratingwaarde' table in database.
 */
class Ratingwaarde extends AbstractRatingwaarde
{
}
